name: Eslint

on:
  push:

permissions:
  contents: read

jobs:
  lint:
    runs-on: "ubuntu-latest"
    permissions:
      # required for all workflows
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install yarn
        run: yarn install --immutable
      - name: Check Linting
        run: yarn sariflint
        continue-on-error: true
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@b611370bb5703a7efb587f9d136a52ea24c5c38c # v3.25.11
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
          category: lint
